# Generated by Django 5.2.15 on 2026-06-06 04:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In Review'), ('UNDER_DISCUSSION', 'Under Discussion'), ('ANSWERED', 'Answered'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('original_question', models.TextField()),
                ('structured_summary', models.TextField(blank=True, null=True)),
                ('structured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('structured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structured_cases', to=settings.AUTH_USER_MODEL)),
                ('warrior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('anonymous_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_revealed', models.BooleanField(default=False)),
                ('parent_display_name_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('quoted_text_snapshot', models.TextField(blank=True, null=True)),
                ('quoted_display_name_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cases.case')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='cases.comment')),
                ('quoted_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='cases.comment')),
            ],
        ),
        migrations.CreateModel(
            name='PublishedAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='published_answer', to='cases.case')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='ACCEPTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='cases.case')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('case', 'doctor'), name='unique_case_doctor_invitation')],
            },
        ),
        migrations.CreateModel(
            name='AmendedAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amended_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amended_answers', to=settings.AUTH_USER_MODEL)),
                ('published_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='cases.publishedanswer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('published_answer', 'version_number'), name='unique_amendment_version')],
            },
        ),
    ]
