# Generated by Django 5.2.15 on 2026-06-06 04:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CASE_TRANSITION', 'Case Transition'), ('CASE_STRUCTURED', 'Case Structured'), ('DOCTOR_INVITED', 'Doctor Invited'), ('COMMENT_CREATED', 'Comment Created'), ('IDENTITY_REVEALED', 'Identity Revealed'), ('ANSWER_PUBLISHED', 'Answer Published'), ('ANSWER_AMENDED', 'Answer Amended'), ('CASE_CLOSED', 'Case Closed'), ('CASE_REJECTED', 'Case Rejected')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events_as_actor', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.case')),
                ('target_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.comment')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_as_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['case', '-timestamp'], name='audit_audit_case_id_4791c1_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_c194db_idx')],
            },
        ),
    ]
